version: 1.0.0+1
name: rich_text_editor_example
description: Example app for testing the rich_text_editor package.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  rich_text_editor:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
